[package]
name = "luau-formatter"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
lazy_static = "1.5.0"
luau-parser = { path = "../parser", default-features = false }
regex = "1.10.6"
